### PR TITLE
fix a typo

### PR DESCRIPTION
**Pull request by wb0330**
89->98,and for my K9GAG08U0F 2GB MLC, the eccpos is from 36 to 483

### CODE REVIEW

**Comment by Reggi3** [comment]
I'm not going to sign off on this straight away, I'm curious as to what testing you've done with this typo?  We found that our driver only works with a specific version of superboot, the actual values were created by the friendlyarm driver  itself, so it could be that superboot also has the same error (they have to match layouts when reading/writing otherwise you get ecc errors everywhere when you boot).

We simply adapted some existing 'debug' code that was in the s3c_nand.c file to use a printk to dump the ecc layout positions, this could actually explain why.

**Comment by wb0330** [comment]
Understood, it's dump from s3c_nand.c for specific version of superboot.  Actually, it's a FriendlyARM's typo, and they fixed it in new version. Also this typo error will not cause any issue, if we only use the start pos and size of the layout, and assume it's continuous distribution in memory.

**Comment by Reggi3** [comment]
We'll sort this out though one way or the other, perhaps we need dumps from all of the different kernel sources to see what they all have for that value?  It was something we wanted to look into because only working with one version of the bootloader seemed wrong to us and we'd prefer that the driver works with as many target boards and images as possible.

**Comment by wb0330** [comment]
Your driver is great, though i catch many times random crash on my board. I have compared the disassemble result of s5p_nand_mlc.fo and s5p_nand_mlc.o generated by your code, they are  99% similarity.
the superboot was closed source,In order to work on more target boards, It would be better to porting a opensource bootloader. so kangear(https://github.com/kangear/tiny210v2-uboot)  have do some work on it, a version of u-boot can run on MLC nand and enable the HW ECC at BL1 is ready now. Next step  work is to boot the linux kernel. I will try to merger you driver  into u-boot BL2.

**Comment by Reggi3** [comment]
There is also an effort to port to kernel 3.10 by huhu, it seems that we're all trying to get some work done on the 210 devices but we're not very well organised.  There is also a barebox that is 99% working, just needs the nand driver fixing.  I reckon if we get a bit more organised and set some definite goals etc then we can all work together, I suspect that most of the stuff we will be working on will work on all the boards with all the drivers and all of the OS versions except winCE.

**Comment by wb0330** [comment]
Release code on github is a good start for organization

**Pull request closed without merging**
